# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'demoRIBs' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'RIBs', :git => 'https://github.com/uber/RIBs', :tag => 'v0.10.0'
  pod 'SnapKit', '~> 4.0.0'
  pod 'RxCocoa', '~> 5.1'
  # Pods for demoRIBs

end
